################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
bms-stm32/Default/util/delay \
bms-stm32/Default/util/string \
bms-stm32/app \
bms-stm32/app/auth_service \
bms-stm32/app/canopen/app_co_init \
bms-stm32/app/canopen/app_co_od \
bms-stm32/app/canopen/app_co_storage_init \
bms-stm32/app/canopen \
bms-stm32/board \
bms-stm32/board/stm32_bsp/bq_hardware \
bms-stm32/board/stm32_bsp/bq_hw \
bms-stm32/board/stm32_bsp/can_hardware \
bms-stm32/board/stm32_bsp/core_hw \
bms-stm32/board/stm32_bsp/current_sense_hardware \
bms-stm32/board/stm32_bsp/debug_com_port_hardware \
bms-stm32/board/stm32_bsp/delay_hw \
bms-stm32/board/stm32_bsp/ext_flash_hardware \
bms-stm32/board/stm32_bsp/hc05_hw \
bms-stm32/board/stm32_bsp/inrush_limiter_hardware \
bms-stm32/board/stm32_bsp/internal_flash_hw \
bms-stm32/board/stm32_bsp/key_hw \
bms-stm32/board/stm32_bsp/nfc_hardware \
bms-stm32/board/stm32_bsp/node_id_hw \
bms-stm32/board/stm32_bsp/rgb_hw \
bms-stm32/board/stm32_bsp/sdk/CMSIS/Device/ST/STM32F0xx/Source \
bms-stm32/board/stm32_bsp/sdk/STM32F0xx_StdPeriph_Driver/src \
bms-stm32/board/stm32_bsp/soc_hw \
bms-stm32/board/stm32_bsp \
bms-stm32/board/stm32_bsp/temp_sense_hardware \
bms-stm32/build/app \
bms-stm32/build/app/canopen/app_co_init \
bms-stm32/build/app/canopen/app_co_od \
bms-stm32/build/app/canopen/app_co_storage_init \
bms-stm32/build/app/canopen \
bms-stm32/build/board \
bms-stm32/build/board/stm32_bsp/bq_hardware \
bms-stm32/build/board/stm32_bsp/bq_hw \
bms-stm32/build/board/stm32_bsp/can_hardware \
bms-stm32/build/board/stm32_bsp/core_hw \
bms-stm32/build/board/stm32_bsp/current_sense_hardware \
bms-stm32/build/board/stm32_bsp/debug_com_port_hardware \
bms-stm32/build/board/stm32_bsp/delay_hw \
bms-stm32/build/board/stm32_bsp/ext_flash_hardware \
bms-stm32/build/board/stm32_bsp/hc05_hw \
bms-stm32/build/board/stm32_bsp/inrush_limiter_hardware \
bms-stm32/build/board/stm32_bsp/internal_flash_hw \
bms-stm32/build/board/stm32_bsp/key_hw \
bms-stm32/build/board/stm32_bsp/node_id_hw \
bms-stm32/build/board/stm32_bsp/rgb_hw \
bms-stm32/build/board/stm32_bsp/sdk/CMSIS/Device/ST/STM32F0xx/Source \
bms-stm32/build/board/stm32_bsp/sdk/STM32F0xx_StdPeriph_Driver/src \
bms-stm32/build/board/stm32_bsp/soc_hw \
bms-stm32/build/board/stm32_bsp \
bms-stm32/build/board/stm32_bsp/temp_sense_hardware \
bms-stm32/build/component/adc_sensor \
bms-stm32/build/component/afe \
bms-stm32/build/component/cell_array \
bms-stm32/build/component/cell_bank \
bms-stm32/build/component/flash_memory \
bms-stm32/build/component/hc05 \
bms-stm32/build/component/inrush_limiter \
bms-stm32/build/component/keypad \
bms-stm32/build/component/ntc \
bms-stm32/build/component/switch \
bms-stm32/build/libs/selex-libc/canopen_clib \
bms-stm32/build \
bms-stm32/build/service/bms \
bms-stm32/build/service/data_logger \
bms-stm32/build/service/estimator \
bms-stm32/build/service/soc-ekf \
bms-stm32/build/service/soc-ocv \
bms-stm32/build/service/soc-spkf \
bms-stm32/build/service/soc_est \
bms-stm32/build/service/soh_awtls \
bms-stm32/build/service/soh_est \
bms-stm32/build/util/string \
bms-stm32/component/adc \
bms-stm32/component/adc_sensor \
bms-stm32/component/afe \
bms-stm32/component/can \
bms-stm32/component/cell_array \
bms-stm32/component/cell_bank \
bms-stm32/component/ext_flash \
bms-stm32/component/flash_memory \
bms-stm32/component/hc05 \
bms-stm32/component/inrush_limiter \
bms-stm32/component/keypad \
bms-stm32/component/nfc \
bms-stm32/component/ntc \
bms-stm32/component/rgb_led \
bms-stm32/component/switch \
bms-stm32/libs/selex-libc/canopen_clib \
bms-stm32/libs/selex-libc/canopen_clib/test/test_can_msg \
bms-stm32/libs/selex-libc/canopen_clib/test/test_pdo \
bms-stm32/libs/selex-libc/canopen_clib/test/test_sdo \
bms-stm32/libs/selex-libc/test-suit \
bms-stm32 \
bms-stm32/service/auth_service \
bms-stm32/service/bms \
bms-stm32/service/data_logger \
bms-stm32/service/estimator \
bms-stm32/service/fault_handler \
bms-stm32/service/log-flash \
bms-stm32/service/soc-ekf \
bms-stm32/service/soc-ocv \
bms-stm32/service/soc-spkf \
bms-stm32/service/soc_est \
bms-stm32/service/soh_awtls \
bms-stm32/service/soh_est \
bms-stm32/service/task-scheduler \
bms-stm32/test/test_ADC \
bms-stm32/test/test_AFE \
bms-stm32/test/test_CANBus \
bms-stm32/test/test_I2C \
bms-stm32/test/test_Led_RGB \
bms-stm32/test/test_MOSFET_SOFTSTART \
bms-stm32/test/test_MainSwitch \
bms-stm32/test/test_PWM \
bms-stm32/test/test_UART \
bms-stm32/test/test_afe_new \
bms-stm32/test/test_auth_service/mock \
bms-stm32/test/test_auth_service \
bms-stm32/test/test_balancing \
bms-stm32/test \
bms-stm32/test/test_flash \
bms-stm32/test/test_gpio \
bms-stm32/test/test_hc05 \
bms-stm32/test/test_i2c_new_bq \
bms-stm32/test/test_pack_thermal \
bms-stm32/test/test_soc \
bms-stm32/test/test_switch \
bms-stm32/util/delay \
bms-stm32/util/string \

